name : run jankins test

on:
 push:
   branches:
      main
jobs:
   run-unit-test:
      runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v4.2.2

     - name: rununit tests
         run : mvn test
